/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package finanfacileitor;

import javax.swing.JTextField;

/**
 *
 * @author muril
 */
public class TelaCalculoPercentual extends javax.swing.JFrame {

    /**
     * Creates new form Tela
     */
    public TelaCalculoPercentual() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ExecutarCalculoDivisao = new javax.swing.JButton();
        descobrinfoPercentual = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        valorASerMultiplicado = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        mostrandoOPrimeiroValorDivididoPorCem = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        MostrandoResultadoFinal = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ExecutarCalculoDivisao.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ExecutarCalculoDivisao.setText("Executar Cálculo Percentual");
        ExecutarCalculoDivisao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExecutarCalculoDivisaoActionPerformed(evt);
            }
        });

        descobrinfoPercentual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                descobrinfoPercentualActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Digite a porcentagem ex 25%, o valor sera dividido por 100.");

        valorASerMultiplicado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valorASerMultiplicadoActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("O resultado dessa divisão será:");

        mostrandoOPrimeiroValorDivididoPorCem.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        mostrandoOPrimeiroValorDivididoPorCem.setText(".");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Digite o valor que sera multiplicado, o resultado da divisão acima sera multiplicado pelo valor abaixo.");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("O resultado dessa multiplicação será:");

        MostrandoResultadoFinal.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        MostrandoResultadoFinal.setText(".");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Cálculo Percentual");

        jButton1.setText("Sair da Tela");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(descobrinfoPercentual, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addGap(47, 47, 47)
                        .addComponent(mostrandoOPrimeiroValorDivididoPorCem, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ExecutarCalculoDivisao)
                        .addGap(193, 193, 193)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(valorASerMultiplicado, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(MostrandoResultadoFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 623, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(descobrinfoPercentual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(mostrandoOPrimeiroValorDivididoPorCem))
                .addGap(32, 32, 32)
                .addComponent(jLabel4)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(valorASerMultiplicado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(MostrandoResultadoFinal))
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ExecutarCalculoDivisao)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(113, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ExecutarCalculoDivisaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExecutarCalculoDivisaoActionPerformed
        String vs1 = descobrinfoPercentual.getText();
        Double convertendoOvs1 = Double.valueOf(vs1);
        Double convertendoAgoraOvs1 = convertendoOvs1 / 100;
        vs1 = String.valueOf(convertendoAgoraOvs1);
        mostrandoOPrimeiroValorDivididoPorCem.setText(vs1);
        
        String vs2 = valorASerMultiplicado.getText();
        Double convertendoOvs2 = Double.valueOf(vs2);
        Double convertendoAgoraOvs2 = convertendoOvs2 * convertendoAgoraOvs1;
        vs2 = String.valueOf(convertendoAgoraOvs2);
        MostrandoResultadoFinal.setText(vs2);
    }//GEN-LAST:event_ExecutarCalculoDivisaoActionPerformed

    private void valorASerMultiplicadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valorASerMultiplicadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_valorASerMultiplicadoActionPerformed

    private void descobrinfoPercentualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_descobrinfoPercentualActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_descobrinfoPercentualActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCalculoPercentual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCalculoPercentual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCalculoPercentual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCalculoPercentual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCalculoPercentual().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ExecutarCalculoDivisao;
    private javax.swing.JLabel MostrandoResultadoFinal;
    private javax.swing.JTextField descobrinfoPercentual;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel mostrandoOPrimeiroValorDivididoPorCem;
    private javax.swing.JTextField valorASerMultiplicado;
    // End of variables declaration//GEN-END:variables
}
